### Health check
GET http://localhost:8080/healthz

### ListUsers
GET http://localhost:8080/users

### GetUser
GET http://localhost:8080/users/1

### CreateUser
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Adam"
}

### DeleteUser
DELETE http://localhost:8080/users/1

### AWS
GET https://3i11yqzhg6.execute-api.us-east-1.amazonaws.com/prod/users