AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless REST API

Globals:
  Function:
    Runtime: go1.x
    Timeout: 10
    MemorySize: 512

Resources:
  
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: cmd/user-service/main.zip
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
