AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless REST API
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: src/main.zip
      Runtime: go1.x
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 10
      Events:
        ApiCall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
