// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Sigv4Scopes = "sigv4.Scopes"
)

// Input for creating a user.
type CreateUser struct {
	// Name of the user.
	Name string `json:"name"`
}

// Input for updating a user.
type UpdateUser struct {
	// Name of the user.
	Name string `json:"name"`
}

// User.
type User struct {
	// Attachment identifier.
	Id openapi_types.UUID `json:"id"`

	// Name of the user.
	Name string `json:"name"`
}

// Response for list of Users
type UsersList = []User

// Id defines model for id.
type Id = openapi_types.UUID

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody = CreateUser

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody = UpdateUser

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return a list of user.
	// (GET /users)
	ListUsers(ctx echo.Context) error
	// Create an user.
	// (POST /users)
	CreateUser(ctx echo.Context) error
	// Deletes a user.
	// (DELETE /users/{id})
	DeleteUser(ctx echo.Context, id Id) error
	// Get an user.
	// (GET /users/{id})
	GetUser(ctx echo.Context, id Id) error
	// Update an user.
	// (PUT /users/{id})
	UpdateUser(ctx echo.Context, id Id) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListUsers converts echo context to params.
func (w *ServerInterfaceWrapper) ListUsers(ctx echo.Context) error {
	var err error

	ctx.Set(Sigv4Scopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ListUsers(ctx)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	ctx.Set(Sigv4Scopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// DeleteUser converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Sigv4Scopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteUser(ctx, id)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Sigv4Scopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUser(ctx, id)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Sigv4Scopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateUser(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/users", wrapper.ListUsers)
	router.POST(baseURL+"/users", wrapper.CreateUser)
	router.DELETE(baseURL+"/users/:id", wrapper.DeleteUser)
	router.GET(baseURL+"/users/:id", wrapper.GetUser)
	router.PUT(baseURL+"/users/:id", wrapper.UpdateUser)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yYbW/bNhDHv4pwC1BgkPzUdKv1zs5DESxbsjjBOsRBQEtniYVEaiTlxDX03QeeZFmO",
	"1SUNEqDb+qaupSPv7n8/3oVeQSDTTAoURoO/gowplqJBRd94aP8NUQeKZ4ZLAT6chCgMn3NUjpw7uUYF",
	"LuA9S7MEwYd+gMPebP7eG/QGQ29/GAbee8Z+8sLhu2GAw8GcDWfgArdbZczE4IJgqV3JQ3BB4V85VxiC",
	"b1SOLuggxpTZKOZSpcyAD3lOlmaZ2VXaKC4iKIpibUyRHyhkBq9sdLsZiCw3zlwqJ7BWXEQOo0Q64EKm",
	"ZIbKcKRtytAebvAbS9Emb2Ks120UGMtZS3jN1K7LfW9qKzn7hIGBwoWrLHxC3Lm1+rbibo34qjW4NqpG",
	"xrAgTlEYh9eAdZ5D1iOcuK+mDXn7R4H0Kddm1/UF6kwKjVTahGtj4yB7e1AMpqTansI5+PBDd3NguxXw",
	"XVK/qL0ypdiS4tMY5Iqb5cQaluprHi32qQzWd4wspBNcHcJRbmKp+GdGsW12zPgvuAQX7j2Wss9SeCzj",
	"ETN4x5Yey028trvTE9qfziMXc9lSauGMzk8cI52UCRaVcmurt+GG1KYH1gO4sECly3WDXn/o9fte72eb",
	"qsxQWAsf3nZ6nZ6FjJmYMuzSevu/CFvlNrkS2mG11nUAllLK/CQEH2y11mVQVY1o20GvZz8CKQwK8sCy",
	"LOEBLe1+0tbNqtG6HitdyQVJth3qVoDOOoatyoJ/Xdf0+qa4cUHnacrUss70QaIkNIu0RZa69017Vbkw",
	"GJVq2BxiY7Jf0cTSKnN+NrkkxbU2sZJ5FI8xZgsuFfggcEFEbZC4zZS8t/Tkitu9joXvT/IZkSr8vdXo",
	"j4nvnzNluPVW+Jso1i8vMKI3CUtnIfNtqbuDXv+d13vrve1357kI7FLd3VuNMn5cfe2MlF3DF9jlYiHL",
	"+uhS6Ey2HcVybDhMkFQOE6GjKlzWjWEHk8aoKRsCajOW4fLFEGk4KLabjp2RxQ6c/ReFs41LtunWXw3l",
	"tsT/eRprpUYZPyX7L1NZuFXv6q54WJR0JmhaptUhPdfV/N9BsnxdIdn8k+66vd4bky4PwdbrVftdG1J0",
	"3sp0w6+HaluP7y2OBH5k+pHiM6YxdKRwuHmjHR7uTsEPaP59IG0AcmG/t78rw2XVzZ1QonaENA7ec206",
	"TybuA5r/TQ974kTNW3Ar7zONQboWbYezxs3n2ai9/OxtRPWNzF6ili6Az2mUdT2+k1tP3aI96fXnVoXH",
	"o8Pbi6Pfr44ml7fjs8M/7bO1wfnWbyfV8vXLTnnT6oyCALX2DqQwSibeKEnknXemeETXsTc/voEGVJeY",
	"ZgkzpetdlGA1BVRKqgMZ4hR8ZwpjFl5sjsEUXGcKKWrNospgj+C8Nx1a2FmwhIe055H9PqGr7RQKAurw",
	"6Hh0dXp5u//x42vk2fDw7pU8fKG0VafwquwJVZYk8ETrshxJYj+qh3jRbD7lb1cPXjWTouZRFH8HAAD/",
	"/xia2Rt+EwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
