openapi: 3.0.0

info:
  title: users-api
  description: An API to manage users.
  version: "2019-11-07"
  
paths:

  /healthz:
    get:
      summary: Healthcheck.
      operationId: GetHealth
      description: Returns a HealthCheck status
      responses:
        '200':
          description: Healthcheck response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'

  /users/{userID}:
    get:
      summary: Get an user.
      operationId: GetUser
      description: Returns a user based on it's ID.
      tags:
      - user
      parameters:
        - $ref: '#/components/parameters/userID'
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: The user does not exist.

    put:
      summary: Update an user.
      operationId: UpdateUser
      description: Update and return an user
      tags:
      - user
      parameters:
        - $ref: '#/components/parameters/userID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserInput'
      responses:
        '201':
          description: user updated response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    delete:
      summary: Deletes a user.
      operationId: DeleteUser
      description: Deletes a user
      tags:
      - user
      parameters:
        - $ref: '#/components/parameters/userID'
      responses:
        '200':
          description: user deleted response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users:
    get:
      summary: Return a list of user.
      operationId: ListUsers
      description: Returns a list of users.
      tags:
      - user
      responses:
        '200':
          description: list of users response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersList'

    post:
      summary: Create an user.
      operationId: CreateUser
      description: Create an user and returns the user
      tags:
      - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserInput'
      responses:
        '201':
          description: created user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  parameters:
    userID:
      name: userID
      in: path
      description: Identifier of user
      required: true
      example: 1
      schema:
        type: integer
  schemas:
    HealthCheckResponse:
      description: Healthcheck endpoint reponse
      type: object
      properties:
        message:
          type: string
          example: ok
  
    User:
      description: User.
      type: object
      required:
        - userID
        - name
      properties:
        userID:
          type: string
          format: uuid
          description: User identifier.
          example: 1ce90bf8-2029-49dc-8aa6-d959ce92fa9b
        name:
          type: string
          description: Name of the user.
          example: Bob
       
    CreateUserInput:
      description: Input for creating a user.
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the user.
          example: Bob

    UpdateUserInput:
      description: Input for updating a user.
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the user.
          example: Bob
 
    UsersList:
      description: Response for list of Users
      type: array
      items:
        $ref: '#/components/schemas/User'