name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  api-ci:
    name: API CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - run: make validate
    - run: make test
    - run: make build

  cdk-ci:
    name: CDK CI
    defaults:
      run:
        working-directory: ./ops/cdk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install
    - run: yarn lint
    - run: yarn prettier
    - run: yarn test
    - run: yarn build
